# 对话设置
conversation_setting:

  system: "现在你是一位金牌带货主播，你的名字叫{role_type}，你的说话方式是{character}。你能够根据产品信息讲解产品并且结合商品信息解答用户提出的疑问。"
  first_input: "我的{product_info}，你需要根据我给出的商品信息撰写一段直播带货口播文案。你需要放大商品的亮点价值，激发用户的购买欲。"


# 数据集生成设置
data_generation_setting:

  # 每个产品生成 ${each_product_gen} 个 conversion 数据，conversion 中包含【文案 + QA】，
  each_product_gen: 3

  # 每个 conversion 中的的对话数，文案为 1 个，其余会生成 ${each_conversation_qa} - 1 个 QA 
  each_conversation_qa: 5

  # 每个文案生成随机抽取 ${each_pick_hightlight} 个亮点
  each_pick_hightlight: 3

  # 每个文案生成后随机抽取 ${each_pick_hightlight} 个问题生成用户的提问
  each_pick_question: 3

  # 数据集生成 prompt
  dataset_gen_prompt: 现在你是一位金牌带货主播，你的名字叫{role_type}，你的说话方式是{character}。
                      我的{product_info}，你需要根据我给出的商品信息撰写一段至少600字的直播带货口播文案。你需要放大商品的亮点价值，激发用户的购买欲。
                      输出文案后，结合商品信息站在消费者的角度根据[{customer_question}]提出{each_conversation_qa}个问题并解答。
                      全部输出的信息使用我期望的 json 格式进行输出：{dataset_json_format}。注意 json 一定要合法。
 
  # 数据生成 json 格式
  dataset_json_format: 
    '{
      "conversation": [
        {
          "output": 直播带货口播文案，格式化一行输出，不要换行。
        },
        {
          "input": 消费者的问题,
          "output": 主播回答
        },
        {
          "input": 消费者的问题,
          "output": 主播回答
        },
        ... 直到问题结束
      ]
    }'

# 说明书生成设置
instruction_generation_setting:
  # 说明书生成 prompt
  dataset_gen_prompt: 我上传的是一个产品的详细说明，请帮我生成 markdwon 格式的说明书，需要包含产品名字、产品细节详情、卖点、亮点，越详细越好，只输出说明书即可。


# 角色及其性格
role_type:
  乐乐喵: # 萝莉
    - 甜美
    - 可爱
    - 熟练使用各种网络热门梗造句
    - 称呼客户为[家人们]

# 商品信息结构体
product_info_struct:
  - 商品名是[{name}]，
  - 商品的亮点是[{highlights}]

# prompt: 购买东西时候，客户常会问题的问题，举例10个, 只列举大类就行
customer_question_type:
  - 价格与优惠政策
  - 产品质量与性能
  - 尺寸与兼容性
  - 售后服务
  - 发货与配送
  - 用户评价与口碑
  - 包装与附件
  - 环保与安全
  - 版本与型号选择
  - 库存与补货

# 第一个 prompt: 帮我列举10种常用的消费品种类，并每种举例5个其子类
# 每个类 prompt: 现在你精通任何产品，你可以帮我举例每个产品的6个亮点或特点，, 然后用python dict形式输出：{类名：[特点1, 特点2] ...} ，去掉特点12的字样，除python字典外的其他都不要输出，不要有任何的警告信息。 [xxx]
product_list:
  个人护理与美妆:
    口腔护理:
      漱口水: [深度清洁, 消除口臭, 抗菌消炎, 提神醒齿, 旅行装方便, 口感舒适]
      牙刷: [软毛设计, 有效清洁, 不同刷头适应不同需求, 防滑手柄, 定期更换刷头, 便携式包装]
      牙线: [清除牙缝食物残渣, 预防牙周病, 细密设计适合各种牙缝, 便于携带, 独立包装卫生, 无损牙齿表面]
      牙膏: [清洁牙齿, 防止蛀牙, 清新口气, 多种口味选择, 易于携带, 温和不刺激]
      电动牙刷: [高效清洁, 减少手动压力, 定时提醒, 智能模式调节, 无线充电, 噪音低]
    彩妆:
      口红: [丰富色号, 滋润保湿, 显色度高, 持久不脱色, 易于涂抹, 便携包装]
      眼影: [多色搭配, 细腻质地, 持久不掉色, 提升眼部层次, 防水防汗, 专业级效果]
      睫毛膏: [浓密增长, 卷翘持久, 纤维纤长, 防水防泪, 易卸妆, 速干配方]
      粉底液: [轻薄透气, 遮瑕力强, 持久不脱妆, 适合各种肤质, 调整肤色, 携带方便]
      腮红: [自然提亮, 持久显色, 多种色调, 易于上妆, 适合日常和特殊场合, 温和不刺激]
    护肤:
      洁面乳: [温和清洁, 深层卸妆, 适合各种肤质, 易冲洗, 保湿滋润, 无刺激]
      爽肤水: [收缩毛孔, 平衡肌肤酸碱度, 清爽不油腻, 补充水分, 调理肌肤状态, 快速吸收]
      精华液: [高浓度活性成分, 深度滋养, 改善肤质, 淡化细纹, 提亮肤色, 修复功效]
      面膜: [密集滋养, 深层补水, 急救修复, 快速见效, 定期护理, 多种类型选择]
      面霜: [锁水保湿, 持久滋润, 防晒隔离, 抗衰老, 适合四季使用, 易于推开涂抹]
    洗护发:
      发膜: [深度滋养, 强韧发丝, 修复损伤, 改善发质, 定期使用效果显著, 长期护理]
      护发精油: [快速吸收, 持久光泽, 修复损伤, 防静电, 轻盈不沉重, 多种香味可选]
      护发素: [补充水分, 改善干燥, 修复分叉, 增加光泽, 柔软顺滑, 快速吸收]
      洗发喷雾: [随时补充水分, 定型效果, 清爽不油腻, 方便携带, 无硅油配方, 快速修复毛躁]
      洗发水: [温和配方, 深层清洁, 滋养头皮, 丰富泡沫, 易冲洗, 适合各种发质]
    香水:
      古龙水: [清爽不黏腻, 男性专用, 活力气息, 日常喷洒, 木质或草本基调, 商务场合适宜]
      女士香水: [浪漫优雅, 花香调为主, 情感表达, 适合各种年龄, 瓶身设计精致, 提升女性魅力]
      淡香水: [持久轻盈, 清新自然, 日常适用, 不易出汗, 适合敏感肌肤, 四季皆宜]
      男士香水: [阳刚之气, 木质或烟草调, 商务或运动时使用, 持久耐闻, 体现自信, 功能性与时尚结合]
      香精: [香味浓郁, 留香时间长, 适用于特殊场合, 浓度高, 适合追求奢华感, 独特个性]
  书籍与文化用品:
    办公文具:
      便签纸: [便携式, 即时记录, 可撕毁, 环保材料, 颜色丰富, 大小适中]
      打印机耗材: [高打印质量, 兼容多种打印机, 寿命长, 环保型可选, 节省成本, 快速更换]
      文件夹: [分类存储, 透明或标示设计, 耐用, 不同尺寸和材质, 易于查找, 整理文件的好帮手]
      笔: [耐用性, 可书写性, 不同颜色和类型, 轻便设计, 环保材料, 易于携带]
      笔记本: [多页选项, 多样性（线圈装订、活页等）, 可写性强, 不同尺寸和封面设计, 易于整理, 适合做笔记]
    教育:
      教辅教材: [针对性强, 习题丰富, 权威作者, 同步课堂, 解析详细, 知识点全面]
      科普读物: [科学知识普及, 图文并茂, 通俗易懂, 激发兴趣, 严谨数据支持, 跨学科融合]
      职业技能: [实战案例分析, 专业技能培养, 行业最新动态, 职业资格认证, 线上线下结合, 持续更新]
      育儿教育: [专家指导, 亲子活动, 阶段发展指南, 情感教育, 行为塑造, 科学育儿理论]
      英语学习: [听说读写训练, 互动式教学, 分级设计, 多媒体资源, 词汇扩充, 语法精讲]
    文学:
      传记: [真实故事, 人物刻画细腻, 历史背景, 启发人生, 研究价值, 文化传承]
      剧本: [对话生动, 舞台指示明确, 冲突紧张, 角色互动, 戏剧张力, 影视改编潜力]
      小说: [丰富的情节, 多元角色, 深度主题, 叙事性强, 想象力十足, 文学价值]
      散文: [语言优美, 情感真挚, 结构自由, 思想深邃, 个人化表达, 易于阅读]
      诗歌: [韵律美感, 象征隐喻, 情感抒发, 形式多样, 音乐性, 永恒主题]
    杂志:
      新闻时政: [即时资讯, 深度分析, 国际视野, 政策解读, 社会热点, 舆论追踪]
      旅游: [目的地推荐, 旅行攻略, 文化探索, 户外活动, 美食游记, 旅行故事]
      时尚杂志: [潮流趋势, 设计师访谈, 时尚搭配, 美容护肤, 名人动态, 生活方式]
      生活: [健康养生, 家庭生活, 美食烹饪, 家居设计, 亲子教育, 生活技巧]
      科技: [最新科技, 创新产品, 技术解析, 行业动态, 未来趋势, 评测与体验]
    艺术:
      摄影: [瞬间捕捉, 纪实与艺术并存, 光线与构图的艺术, 记录生活与历史, 后期处理技术多样, 视觉故事讲述者]
      绘画: [丰富的色彩表达, 创意无限, 视觉艺术形式, 个人情感传达, 传统与现代技术结合, 跨媒介创作]
      舞蹈: [身体语言的表达, 节奏感与协调性, 情感释放与叙事, 各种风格多样性, 创新编舞与剧场表现, 健身与娱乐结合]
      设计: [用户体验至上, 功能与美学融合, 创新解决问题, 跨领域应用广泛, 可持续性考虑, 视觉传达专家]
      音乐: [情感共鸣, 节奏与旋律的魅力, 多元文化交融, 现场表演震撼力, 数字化制作技术, 作曲与编曲技巧]
  健身与户外用品:
    健身器材:
      动感单车: [阻力可调, 内置健身程序, 舒适座椅, 实时数据显示, 高强度训练设备, 紧凑空间设计]
      哑铃: [多种重量选择, 便携式设计, 锻炼肌肉全面, 无器械环境适用, 适合家庭使用, 易于储存]
      拉力绳: [弹力可调节, 小巧便携, 全身锻炼工具, 适合旅行使用, 易于收纳, 多功能训练组件]
      瑜伽垫: [防滑材质, 吸湿排汗, 厚度适中, 耐用易清洁, 各种瑜伽动作适用, 轻巧便携]
      跑步机: [心率监测, 多功能运动模式, 大承重设计, 智能显示屏, 折叠方便, 安全锁定装置]
    户外装备:
      冲锋衣: [快干面料, 防风防雨, 透气透湿, 可拆卸帽子, 多功能口袋, 适应户外运动]
      帐篷: [便携式, 防风雨, 易于搭建, 通风透气, 耐用, 适合户外活动]
      徒步鞋: [抓地力强, 缓震减压, 透气排汗, 防滑耐磨, 适应多种地形, 可调节鞋带]
      登山包: [大容量, 分隔储物空间, 背负系统舒适, 耐磨耐用, 防水拉链, 多用途]
      睡袋: [保暖性能好, 轻便, 压缩设计, 适合各种睡眠姿势, 防水材料, 不同季节选择]
    水上运动:
      冲浪板: [流线型设计, 高强度材料, 适应多种浪型, 重量轻便, 稳定操控, 适合不同技能水平]
      救生衣: [国际认证, 浮力强, 舒适贴身, 多尺寸选择, 反光条保证可见, 紧急释放系统]
      浮潜套装: [一体式设计, 快速穿脱, 保暖透气, 包含呼吸管, 便于携带储存, 适合初学者]
      游泳圈: [安全可靠, 易于携带, 适合各种年龄, 可调节大小, 充气快速, 耐用]
      潜水镜: [防水防雾, 高清视野, 舒适贴合, 可更换镜头, 防紫外线, 耐压设计]
    运动服饰:
      运动T恤: [轻便, 速干, 抗菌, 透气, 多种图案选择, 易于搭配]
      运动内衣: [亲肤, 弹力好, 速干, 防震, 透气性佳, 塑形效果]
      运动帽: [防晒, 吸汗, 轻巧, 调节大小, 时尚配饰, 保护眼睛]
      运动裤: [快干, 伸缩自如, 吸湿排汗, 防风保暖, 高腰设计, 多口袋实用]
      运动鞋: [舒适, 耐磨, 透气, 缓震, 适应多种运动, 时尚设计]
    骑行用品:
      头盔: [安全保障, 减震设计, 透气舒适, 符合安全标准, 可调节大小, 不同风格]
      手套: [防滑抓握, 保护手部, 透气吸汗, 耐磨耐寒, 可调节松紧, 适应各种天气]
      自行车: [环保出行, 便携折叠, 锻炼身体, 节省空间, 耐用结构, 多种款式]
      自行车灯: [夜间骑行必备, LED高亮, 防水防尘, 多种模式选择, 易于安装, 持久续航]
      骑行服: [防风保暖, 吸湿排汗, 反射条纹, 耐磨防刮, 适合四季穿着, 通风透气]
  宠物用品:
    宠物护理:
      宠物牙刷: [硅胶软毛, 防滑手柄, 清洁效果好, 适合各种口腔, 可替换刷头, 定期护理]
      指甲剪: [安全圆角设计, 锋利易剪, 不同大小尺寸, 便于握持, 耐用不易生锈, 儿童和成人适用]
      狗狗沐浴露: [天然成分, 无刺激, 温和清洁, 快速干燥, 多种香味选择, 专为狗狗肤质定制]
      猫砂: [环保可降解, 吸湿性强, 无尘设计, 易清理, 适合各种猫咪, 通风透气]
      除蚤项圈: [长效防蚤, 舒适材质, 防水设计, 易于佩戴, 无毒无害, 定期更换]
    宠物服饰与床具:
      宠物垫: [吸湿透气, 防滑底座, 抗菌材质, 易清洁, 舒适软垫, 多种图案]
      宠物窝: [柔软内衬, 保暖隔音, 可调节大小, 便携式, 环保材质, 易于清洁]
      宠物衣服: [保暖设计, 舒适材质, 可拆洗设计, 多种尺寸选择, 时尚款式, 季节适用]
      牵引绳: [高强度材料, 防勒设计, 伸缩自如, 易握手柄, 耐用, 各种颜色]
      猫树: [攀爬设计, 娱乐玩具, 磨爪板, 安全稳固, 多层空间, 环保无味]
    宠物玩具:
      狗骨头: [天然素材, 口感丰富, 满足狗狗啃咬欲望, 促进口腔健康, 多种口味选择, 安全无毒]
      猫抓板: [耐用耐磨, 吸引猫咪爪痕, 可磨爪训练, 环保无害材料, 设计吸引猫, 易清洁]
      鱼缸装饰: [美观大方, 增强观赏性, 生态仿真, 易于维护, 适合各种鱼类生活, 可调节光照效果]
      鸟类玩具: [模拟自然环境, 刺激鸟儿活动, 色彩鲜艳, 耐用不易损坏, 能发出声音吸引鸟, 有助于智力开发]
      鼠笼配件: [设计合理, 坚固耐用, 易于组装, 提供不同活动空间, 无声滑轮减少噪音, 可调节高度]
    宠物零食:
      冻干肉粒: [锁鲜技术, 高蛋白, 方便保存, 即食健康, 无防腐剂, 适合旅行或训练]
      宠物饼干: [天然成分, 低糖低脂, 口感酥脆, 营养均衡, 满足口感欲望, 便于携带]
      狗咬胶: [无添加, 耐咬设计, 口腔清洁, 锻炼牙齿, 持久美味, 可携带零食]
      猫罐头: [高品质肉类, 丰富口感, 易消化, 维生素补充, 湿粮营养全面, 适合不同口味]
      营养膏: [快速吸收, 补充营养, 易于涂抹, 增强免疫力, 补充能量, 特别适合老年宠]
    宠物食品:
      兔粮: [草本纤维, 低脂低糖, 富含维他命C, 帮助维持消化健康, 无添加剂, 颗粒细腻适合兔子]
      狗粮: [均衡营养, 肉类来源多样, 低敏配方, 有助于牙齿健康, 适合不同体型狗狗, 可口适口]
      猫粮: [高品质蛋白质, 易消化, 维生素和矿物质丰富, 适合不同阶段猫咪, 口感吸引, 无谷物配方]
      鱼饲料: [高蛋白, Omega-3丰富, 易于消化, 颜色和形状吸引鱼类, 天然成分, 适合各种水族]
      鸟食: [丰富的种子和果实, 平衡营养, 添加了必需氨基酸, 有助于羽毛生长, 大小适中便于啄食, 多种口味]
  家居用品:
    厨房用具:
      刀具: [高硬度材质, 切割顺畅, 防滑手柄, 人体工学设计, 抗菌处理, 安全圆角设计]
      炒锅: [不粘涂层, 耐磨耐用, 导热快, 易清洗, 多种烹饪方式, 设计人性化]
      炖锅: [耐高温, 保温性能好, 炖煮效果佳, 大容量, 多功能炖煮模式, 易清洁]
      砧板: [抗菌材质, 防霉易清洗, 耐磨耐刮, 大小适中, 分隔区设计, 环保无毒]
      餐具: [环保材料, 安全无毒, 美观大方, 耐高温, 易消毒, 轻便携带]
    家具:
      书桌: [学习工作专用, 桌面宽敞, 储物抽屉, 高度可调, 耐用材料, 简约现代设计]
      床: [睡眠质量好, 尺寸适中, 床垫舒适, 储物空间, 风格多样, 耐久材料]
      沙发: [舒适度高, 设计多样, 可调节角度, 耐用, 易于清洁, 空间节省]
      衣柜: [容量大, 分类明确, 防尘设计, 易滑动隔板, 折叠或可移动, 多种门款式]
      餐桌椅: [实用性强, 稳固结构, 多种材质选择, 易于组装, 人体工学设计, 可扩展组合]
    床上用品:
      床单: [舒适透气, 易清洗, 多种尺寸选择, 色彩丰富, 耐用, 环保材料]
      床垫: [独立弹簧, 舒适度高, 减压透气, 耐用性强, 支持定制尺寸, 健康环保]
      枕头: [人体工学设计, 记忆棉填充, 支撑颈椎, 抗菌防螨, 多硬度选择, 可机洗]
      毛毯: [保暖效果好, 轻便携带, 多种款式风格, 快速吸湿排汗, 易于存储, 季节通用]
      被罩: [适合各种床型, 可调节扣设计, 亲肤材质, 四季适用, 易搭配, 易脱卸]
    清洁用品:
      垃圾袋: [厚实耐用, 防漏设计, 环保可降解, 不同尺寸选择, 易封口, 透明便于分类]
      拖把: [纤维材质吸水性强, 灵活轻便, 可拆卸清洁, 耐用不易断, 有多种头型可供选择, 易于收纳]
      洗洁精: [强力去油, 快速溶解, 无残留, 天然成分, 不伤手, 适用各种餐具]
      洗衣液: [高效去污, 温和不伤衣物, 易漂洗, 环保配方, 持久留香, 适用于各种面料]
      消毒液: [99.9%杀灭细菌, 快速挥发, 安全环保, 广谱抗菌, 可用于衣物和表面, 便捷喷雾设计]
    装饰品:
      地毯: [吸音保暖, 耐磨耐脏, 色彩丰富, 防滑设计, 环保材料, 家居风格匹配]
      抱枕: [舒适柔软, 多种款式, 可定制图案, 季节适用, 易于更换, 实用装饰]
      挂画: [艺术装饰, 易安装, 个性化设计, 多尺寸选择, 环保材质, 耐久]
      摆件: [收藏价值, 小巧精致, 主题丰富, 搭配空间, 手工制作, 易于清洁]
      窗帘: [遮光透光, 隐私保护, 节能环保, 多种材质, 易清洗, 调节室内光线]
  服装:
    女装:
      上衣: [多口袋设计, 不同领型选择, 适合各种体型, 时尚潮流元素, 材质多样, 易配下装]
      半身裙: [百搭单品, 高腰设计, 裙长可选, 修身显瘦, 便于活动, 季节性强]
      套装: [成套搭配, 节省搭配时间, 统一风格, 专业职场选择, 适合正式场合, 季节性款式丰富]
      裤子: [经典直筒, 修身剪裁, 耐磨耐穿, 弹性适中, 适应多种裤脚, 四季适用]
      连衣裙: [时尚设计, 多种款式, 易搭配, 舒适面料, 适合各种场合, 四季皆宜]
    男装:
      T恤: [休闲百搭, 速干吸汗, 时尚印花设计, 圆领/V领选择, 棉质或混纺材质, 适合夏季穿着]
      休闲裤: [舒适宽松, 多口袋设计, 休闲风格, 适应多种体型, 易于打理, 四季通用]
      牛仔裤: [耐磨耐穿, 经典蓝色, 直筒/修身/喇叭腿选择, 百搭单品, 可正式可休闲, 流行元素融入]
      衬衫: [经典款式, 多色可选, 适合各种场合, 易搭配, 舒适透气, 四季皆宜]
      西装: [正式商务, 精致裁剪, 多样颜色与款式, 耐用, 配饰齐全, 提升专业形象]
    童装:
      儿童T恤: [舒适面料, 可调节肩带, 卡通图案, 易穿脱, 透气吸汗, 适合日常活动]
      儿童裙子: [蓬松设计, 公主裙款式, 安全无毒染料, 多种颜色选择, 适宜季节穿着, 可爱花边装饰]
      儿童裤子: [弹性腰围, 耐磨布料, 易搭配, 适合运动, 拉链或纽扣闭合, 不同长度可供选择]
      婴儿连体衣: [无缝设计, 柔软纯棉, 方便换尿布, 可调节系带, 保暖性强, 无刺激标签]
      学龄前服装: [实用口袋, 活泼色彩, 时尚图案, 合身剪裁, 耐用不易褪色, 学习活动专用]
    配饰:
      围巾: [保暖, 时尚款式, 多种材质选择, 季节适用, 装饰性强, 易搭配]
      帽子: [保护头部, 防寒防晒, 潮流设计, 吸汗透气, 适合户外活动, 可调节款式]
      手套: [保暖效果好, 防风防水, 触感舒适, 耐用, 不同功能分类, 适用于各种天气]
      手表: [精准时间显示, 智能功能, 时尚外观, 健康监测, 耐用电池, 多种风格选择]
      眼镜: [视力保护, 防蓝光, 抗紫外线, 舒适轻便, 可更换镜片, 时尚框架设计]
    鞋履:
      休闲鞋: [舒适休闲, 款式多样, 易于搭配, 适合日常生活, 材质轻巧, 耐穿]
      凉鞋: [夏季必备, 通风凉爽, 轻盈款式, 时尚潮流, 便于行走, 适合海滩度假]
      皮鞋: [正式场合佳选, 质感优良, 经典款式, 耐用性好, 易于打理, 提升职业形象]
      运动鞋: [透气性好, 轻便耐磨, 缓震设计, 多种风格可选, 适合各种运动, 易搭配服装]
      靴子: [保暖防寒, 结实耐用, 多种高度可选, 时尚百搭, 防水防滑, 季节转换实用]
  汽车:
    汽车养护:
      润滑油: [长寿命, 高效润滑, 抗磨保护, 高低温适用, 易流动性, 防腐蚀]
      清洗剂: [强力去污, 温和无损, 多功能用途, 快速溶解, 环保配方, 安全无刺激]
      玻璃水: [无残留, 清晰视线, 雨刮器友好, 快速蒸发, 抗静电, 冬季防冰]
      轮胎蜡: [防水防尘, 增强光泽, 耐磨擦, 紫外线防护, 容易涂抹, 持久效果]
      防冻液: [防冻性好, 沸点高, 防腐蚀, 防锈, 四季通用, 环保配方]
    汽车内饰:
      座垫: [舒适性, 可调节, 耐用, 易安装, 透气, 四季适用]
      方向盘套: [防滑设计, 人性化握感, 多种款式选择, 易拆卸清洗, 耐磨耐高温, 安全操控]
      脚垫: [防滑, 耐磨, 易于清洁, 定制尺寸, 吸音减震, 环保材料]
      行车记录仪: [高清录像, 夜视功能, 广角视野, 碰撞感应, GPS定位, WIFI分享]
      车载香水: [清新香味, 持久挥发, 无毒环保, 装饰性强, 驱除异味, 可调节雾量]
    汽车配件:
      刹车片: [高性能摩擦材料, 耐磨性强, 热稳定性好, 噪音低, 快速制动, 安全可靠]
      机油滤芯: [高效过滤, 长寿命设计, 易安装, 环保材料, 耐高温, 低维护]
      火花塞: [精确点火, 耐高温高压, 电极寿命长, 燃油经济性佳, 低排放, 多种类型适合不同引擎]
      空气滤芯: [高效率空气净化, 抗尘性能强, 可清洗型, 轻量化设计, 耐用, 低阻力]
      雨刮器: [强劲刮水, 防冻设计, 静音运行, 可调节角度, 耐腐蚀, 自动感应雨水功能]
    自驾游装备:
      急救包: [全面急救用品, 小型便携, 包含常用药品, 应急指南, 防水包装, 符合安全标准]
      车载充气床: [快速充气, 舒适睡眠, 耐用材料, 可调节尺寸, 轻巧便携, 易于收纳]
      车载工具箱: [多用途工具, 坚固耐用, 内置收纳, 省空间设计, 适应各种车辆, 易操作]
      车载帐篷: [便携式, 易于安装, 防水设计, 防紫外线, 适合户外活动, 空间利用率高]
      车载烧烤架: [便携式烧烤, 耐高温, 易于折叠, 节省燃料, 适合露营, 安全使用设计]
    车载电器:
      胎压监测: [实时显示胎压, 预警系统, 远程监测, 易于安装, 耐用性好, 节能环保]
      行车记录仪: [高清录像, 夜视功能, 广角视野, 碰撞感应自动录制, GPS定位, WIFI分享]
      车载充电器: [快速充电, USB多口设计, 智能识别设备, 过载保护, 便携式设计, 适配各种车型]
      车载冰箱: [双温区设计, 节能省电, 小型便携, 噪音低, 防震缓冲设计, 内置保温层]
      逆变器: [12V/24V转换, 高效率转换, 多种插头接口, 安全过载保护, 轻巧便携, 适合长途旅行]
  电子产品:
    家用小电器:
      微波炉: [快速加热, 多功率调节, 解冻功能, 烧烤和烤箱模式, 自动菜单选项, 安全防护设计]
      榨汁机: [高速榨汁, 无网设计, 易清洗部件, 多种榨汁模式, 耐用材料, 静音运行]
      电水壶: [快速烧水, 防干烧保护, 一键开关, 多种容量选择, 不锈钢内胆, 自动断电功能]
      电饭煲: [智能预约, 自动保温, 多功能烹饪, 不粘内胆, 易于清洁, 大容量设计]
      空气净化器: [HEPA滤网, 智能感应调节, 静音运行, 自动模式, 空气质量显示, 节能环保]
    智能手机:
      Android手机: [Google Play, 高度可定制, 价格多样, Android 12更新, 品牌众多, 大屏幕选择]
      iPhone: [iOS系统, 流畅体验, A14芯片, Face ID, App Store生态, 设计精美]
      折叠屏手机: [折叠设计, 多任务处理, 大屏显示, 轻薄便携, 创新交互方式, 高端配置]
      游戏手机: [专业级性能, 散热技术, 高刷新率屏幕, 专属游戏模式, 强大音效, 长时间续航]
      老人机: [大字体易读, 简单操作界面, 长电池寿命, 紧急呼叫功能, 健康监测, 耐用性强]
    电脑:
      一体机: [设计简洁, 节省空间, 集成显示, 易于清洁, 触控功能, 适合家庭娱乐]
      二合一电脑: [笔记本和平板两用, 灵活转换模式, 触控和键盘可选, 轻巧便携, 续航持久, 适合教育和商务]
      台式机: [性能强劲, 扩展性强, 大型显示器支持, 可升级部件, 价格相对较低, 适合专业用户]
      平板电脑: [轻薄, 触控操作, 电池续航好, 移动办公便利, 娱乐性强, 适合儿童学习]
      笔记本电脑: [轻便, 便携, 长续航, 触控屏选项, 高性能, 多端口]
    电视与显示器:
      OLED电视: [色彩鲜艳, 对比度极高, 响应速度快, 无背光眩光, 厚度较薄, 自发光无需额外照明]
      投影仪: [大屏幕体验, 便携性好, 可投射到任何平整表面, 灵活性高, 适合大型会议室, 画质受环境光线影响]
      液晶电视: [价格相对较低, 寿命长, 技术成熟, 适合家庭观看, 画质稳定, 安装方便]
      电竞显示器: [刷新率高, 响应时间短, 电竞模式优化, G-Sync/FreeSync, 视野开阔, 适合游戏爱好者]
      电脑显示器: [分辨率高, 色彩准确, 专业级显示效果, 接口丰富, 易于调整角度, 适合办公和设计]
    音频设备:
      头戴式耳机: [高解析度音质, 降噪功能, 大耳罩设计, 长时间佩戴舒适, 物理按键控制, 可调节头带]
      无线耳机: [无线连接, 便携性好, 舒适佩戴, 音质清晰, 触控操作, 续航时间长]
      智能音箱: [语音助手集成, 智能家居控制, 音乐播放能力强, 定时提醒, 可联网更新内容, 学习模式]
      蓝牙音箱: [蓝牙配对方便, 防水防尘, 音量大, 内置麦克风, 多种连接方式, 内置电池便携]
      麦克风: [高灵敏度, 全向拾音, 噪音抑制, USB/3.5mm接口兼容, 适用于直播/会议, 可调节角度]
  食品:
    主食:
      大米: [主食来源, 富含碳水化合物, 易于消化, 营养丰富, 多样烹饪方式]
      燕麦: [高纤维, 低GI, 助消化, 营养均衡, 健康早餐选择]
      玉米: [谷物作物, 富含维生素B, 低脂肪, 易于烹煮, 原生态食品]
      面包: [早餐常见, 面团发酵工艺, 种类繁多, 富含膳食纤维, 即时能量补充]
      面条: [快捷方便, 口感多样, 易于储存, 搭配灵活, 传统食品]
    乳制品:
      冰淇淋: [冷冻甜品, 口感丝滑, 多种口味选择, 夏季消暑, 含有乳脂, 季节性销售]
      奶酪: [营养丰富, 口感细腻, 种类繁多, 可做食材搭配, 需冷藏, 低脂或无脂选项]
      牛奶: [富含蛋白质, 易于消化, 提供钙质, 常温保存, 多种口味, 早餐常见]
      酸奶: [益生菌丰富, 助消化, 口感酸甜, 钙含量高, 冷藏保存, 多样化的口味]
      黄油: [纯正奶油味, 烹饪必备, 富含饱和脂肪, 用于面包涂抹, 冷藏储存, 有不同的脂肪含量]
    果蔬:
      橙子: [维生素C宝库, 口感多汁, 有助于消化, 色泽鲜艳, 季节性水果, 剥皮方便]
      苹果: [口感脆甜, 富含维生素C, 营养丰富, 易于携带, 种类多样, 四季皆有]
      西红柿: [酸甜适中, 富含番茄红素, 烹饪广泛, 低热量, 抗氧化, 四季常见]
      香蕉: [高钾低钠, 易消化吸收, 软糯可口, 有助于心情改善, 便于携带, 热带水果]
      黄瓜: [清爽解渴, 低热量, 高水分, 含有多种维生素, 生食烹饪皆宜, 夏季常吃]
    肉类:
      牛肉: [富含铁质, 营养价值高, 肌肉纤维好, 红白相间纹理, 适合烧烤炖煮, 草食动物来源]
      猪肉: [高蛋白, 易消化, 价格亲民, 营养丰富, 多样做法, 全球消费量大]
      羊肉: [热量高, 补虚暖身, 羊肉汤美味, B族维生素丰富, 适合冬季食用, 草食动物来源]
      鸡肉: [低脂肪, 易吸收, 烹饪方式多样, 蛋白质优质, 胆固醇较低, 全球消费广泛]
      鸭肉: [低脂肪, 滋阴润燥, 蛋白质均衡, 鸭皮脆香, 清热解毒, 烹饪方法多样]
    零食小吃:
      坚果: [富含健康脂肪, 蛋白质丰富, 有助于心脏健康, 多种口味选择, 有助于控制食欲, 营养均衡零食]
      巧克力: [丰富的可可含量, 口感丝滑, 营养丰富, 节日礼品, 含有抗氧化物质, 满足甜食欲望]
      糖果: [甜蜜味道, 各种形状, 小型便携, 节日庆祝必备, 童趣十足, 偶尔享受的零食]
      薯片: [口感酥脆, 多种口味, 方便携带, 零食首选, 富含碳水化合物, 休闲娱乐时享用]
      饼干: [口感香脆, 便于保存, 种类繁多, 低热量选项, 早餐搭配佳品, 适合下午茶]
  饮料:
    咖啡:
      冷萃咖啡: [低咖啡因, 冷热皆宜, 清爽不苦涩, 适合夏季饮用, 慢煮提取技术, 保留更多酸度]
      挂耳咖啡: [包装环保, 冲泡简单, 独立包装, 便于携带, 保存时间较长, 无需清洗咖啡壶]
      浓缩咖啡: [高浓度, 快速提神, 制作工艺复杂, 咖啡豆精选, 用于各种咖啡调制, 口感浓郁]
      研磨咖啡: [新鲜现磨, 口感丰富, 适合咖啡机使用, 深度烘焙选择, 可调整浓度, 风味保持较好]
      速溶咖啡: [便捷, 即溶即饮, 口味多样, 旅行必备, 储存方便, 无需研磨]
    果汁:
      橙汁: [100%纯天然, 维生素C丰富, 清新口感, 无添加防腐剂, 易消化吸收, 适合所有人群]
      混合果汁: [多种口味组合, 营养均衡, 满足不同需求, 口感层次丰富, 便于携带, 适合运动后补充]
      苹果汁: [富含纤维素, 抗氧化能力强, 有助于消化, 口感酸甜适中, 低热量, 适合减肥者]
      菠萝汁: [消化酶含量高, 助消化解腻, 热带风味, 维生素B6丰富, 低脂肪, 夏季清凉饮品]
      葡萄汁: [抗氧化紫红素, 丰富的矿物质, 有助于心血管健康, 天然糖分来源, 口感醇厚, 适合日常饮用]
    瓶装水:
      气泡水: [含有气泡, 提供清新口感, 可助消化, 口感有趣, 通常低糖或无糖, 含有电解质，适合运动后补充水分]
      矿泉水: [含有天然矿物质, 水源地保障, 有益健康, 有助于补充日常所需微量元素, 口感独特, 部分品牌有特定的水质特点]
      纯净水: [无杂质, 口感清爽, 适合各种饮用场景, 便于长期储存, 无矿物质，适合对矿物质需求不高的用户, 包装简洁环保]
    碳酸饮料:
      可乐: [经典口感, 气泡丰富, 甜味适中, 全球品牌, 多种口味, 碳酸饮料]
      柠檬汽水: [柠檬香醇, 酸甜适口, 天然成分, 不含咖啡因, 健康替代品, 夏日必备]
      芬达: [果味浓郁, 多种水果口味, 碳酸饮料, 独特配方, 清凉解暑, 儿童喜爱]
      苏打水: [天然碳酸, 无糖或少糖, 碱性饮料, 助消化, 低热量选择, 调节体内酸碱平衡]
      雪碧: [清爽柠檬味, 无糖或低糖选项, 口感清新, 天然植物成分, 适合解渴, 零度系列]
    茶饮:
      乌龙茶: [半发酵, 复合香气, 减肥效果, 降低胆固醇, 岩韵或果香, 耐泡]
      普洱茶: [熟普陈香, 降脂减肥, 暖胃, 收藏价值, 发酵完全, 老茶醇厚]
      红茶: [红色茶汤, 全发酵, 醇厚口感, 助消化, 含丰富的茶多酚, 适合作为下午茶]
      绿茶: [清香, 无添加, 提神醒脑, 抗氧化, 发酵度低, 利于消化]
      花草茶: [天然植物, 美容养颜, 舒缓情绪, 不含咖啡因, 多种口味选择, 季节性搭配]
